project:
  type: website
  output-dir: docs  # create directory "docs"" to save everything. We added this line in Pallisads workshop

website:
  title: "wmeiring.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

